ProductDetailsResponse Type Date instead of Datetime (#194)
When using datetime for last_used, the following validation error is returned.

pydantic.error_wrappers.ValidationError: 1 validation error for ProductDetailsResponse
last_used
  invalid datetime format (type=value_error.datetime)

The used_date Column is set to Type DATE:
        used_date DATE,

Co-authored-by: Sebastian Rutofski <SebRut@users.noreply.github.com>